# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT atai.wsgi

# beta_settings:
#    cloud_sql_instances: <your-cloudsql-connection-string>

env_variables:
  SECRET_KEY=m3qggt^ki^lutv%pnzxw2&hec9#qpy=uk=zu++%(2^!4&f8fo0

runtime_config:
  python_version: 3
# [END runtime]
